
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: lyrics_api
    ports:
      - "8000:8000"
    env_file:
      - ./.env  
    volumes:
      - ./server/database.db:/app/database.db
    restart: unless-stopped
